name = "backend"
main = "./src/index.ts"
compatibility_date = "2025-01-24"

[build]
command = "npm run build"

[vars]
# The application which will be deployed will pick the environment variable from this file i.e. wrangler.toml and when you'll be accessing/doing something on client, it will be picked from actual .env file 
# And we want the application to connect to the backend using the connection pool and hence putting that URL here and the original DB URL in .env file which has nothing to do with the backend application and may be used while migrating etc
DATABASE_URL= "add your prisma accelerate key!"
JWT_SECRET = "jwt secret key"